services:
  api:
    build: ./api
    container_name: iris-api
    ports:
      - "${API_PORT}:8000"
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS}
    networks:
      - iris-network

  frontend:
    build: ./frontend
    container_name: iris-frontend
    ports:
      - "5174:80"
    depends_on:
      - api
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
    networks:
      - iris-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - iris-network
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - iris-network
    depends_on:
      - prometheus

networks:
  iris-network:
    driver: bridge
